import json
from pathlib import Path

nb_path = Path(r"C:\Users\alvin\Documents\Coolyeah\Skirpsi\Teknikal\fase 2\Generate_Voice_Cloning_Colab.ipynb")

with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Update OpenVoice block in cell 4 to fix MeloTTS / MeCab installation on Colab
cell4_code = [
    "import os\n",
    "import sys\n",
    "import gc\n",
    "import shutil\n",
    "import zipfile\n",
    "import subprocess\n",
    "import urllib.request\n",
    "from pathlib import Path\n",
    "\n",
    "ROOT = Path(\"/content\")\n",
    "INPUT = Path(\"/content/reference_dataskripsi\")\n",
    "REF_ROOT = ROOT / \"reference_dataskripsi\"\n",
    "OUT = ROOT / \"generated_voice_cloning\"\n",
    "REF_ROOT.mkdir(parents=True, exist_ok=True)\n",
    "OUT.mkdir(parents=True, exist_ok=True)\n",
    "DRIVE_OUT = Path(\"/content/drive/MyDrive/data skirpsi/VoiceCloning\")\n",
    "DRIVE_OUT.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "TEXTS = {\n",
    "    \"id\": \"Indonesia adalah negara kepulauan yang kaya budaya, bahasa, sumber daya alam, serta memiliki masyarakat beragam yang hidup saling berdampingan harmonis.\",\n",
    "    \"en\": \"England is a historic European country known for its royal family, famous universities, football, diverse culture, and remarkable technological development worldwide.\",\n",
    "}\n",
    "\n",
    "def run(*args: str, cwd: str | Path | None = None) -> None:\n",
    "    print(\"$\", \" \".join(map(str, args)), flush=True)\n",
    "    subprocess.run(list(map(str, args)), cwd=cwd, check=True)\n",
    "\n",
    "def install(*packages: str) -> None:\n",
    "    run(sys.executable, \"-m\", \"pip\", \"install\", \"--no-build-isolation\", *packages)\n",
    "\n",
    "def free_memory() -> None:\n",
    "    gc.collect()\n",
    "    try:\n",
    "        import torch\n",
    "        if torch.cuda.is_available():\n",
    "            torch.cuda.empty_cache()\n",
    "            torch.cuda.synchronize()\n",
    "    except Exception:\n",
    "        pass\n",
    "\n",
    "def log_memory(tag: str = \"\") -> None:\n",
    "    try:\n",
    "        import torch\n",
    "        if torch.cuda.is_available():\n",
    "            alloc = torch.cuda.memory_allocated() / 1024**3\n",
    "            reserved = torch.cuda.memory_reserved() / 1024**3\n",
    "            print(f\"[mem:{tag}] cuda alloc={alloc:.2f}GB reserved={reserved:.2f}GB\", flush=True)\n",
    "    except Exception:\n",
    "        pass\n",
    "\n",
    "def mp3_from_wav(wav_path: Path, mp3_path: Path) -> None:\n",
    "    run(\"ffmpeg\", \"-y\", \"-i\", str(wav_path), \"-b:a\", \"192k\", str(mp3_path))\n",
    "\n",
    "def extract_dataset() -> None:\n",
    "    drive_folder = Path(\"/content/drive/MyDrive/Dataskripsi\")\n",
    "    if not drive_folder.exists():\n",
    "        candidates = list(Path(\"/content/drive/MyDrive\").rglob(\"*Dataskripsi*\"))\n",
    "        if candidates:\n",
    "            drive_folder = candidates[0]\n",
    "        else:\n",
    "            raise FileNotFoundError(\"Folder 'Dataskripsi' tidak ditemukan di MyDrive Google Drive!\")\n",
    "            \n",
    "    print(f\"📂 Scanning rekursif folder reference dari: {drive_folder}\")\n",
    "    audio_exts = {\".wav\", \".mp3\", \".m4a\", \".ogg\", \".flac\"}\n",
    "    copied_count = 0\n",
    "    \n",
    "    for f in drive_folder.rglob(\"*\"):\n",
    "        if f.is_file() and f.suffix.lower() in audio_exts:\n",
    "            target_name = f.name\n",
    "            if f.suffix.lower() != \".wav\":\n",
    "                target_name = f.stem + \".wav\"\n",
    "                target_path = REF_ROOT / target_name\n",
    "                if not target_path.exists():\n",
    "                    run(\"ffmpeg\", \"-y\", \"-i\", str(f), \"-ar\", \"24000\", \"-ac\", \"1\", str(target_path))\n",
    "                    copied_count += 1\n",
    "            else:\n",
    "                target_path = REF_ROOT / target_name\n",
    "                if not target_path.exists():\n",
    "                    shutil.copy2(f, target_path)\n",
    "                    copied_count += 1\n",
    "    print(f\"  ✅ Found & Prepared {copied_count} reference audio file(s) di {REF_ROOT}\")\n",
    "\n",
    "def scan_speakers() -> dict[str, dict[str, Path]]:\n",
    "    extract_dataset()\n",
    "    speaker_map = {}\n",
    "    \n",
    "    for p in REF_ROOT.glob(\"*.wav\"):\n",
    "        name = p.stem\n",
    "        lang = \"id\"\n",
    "        spk_id = name\n",
    "        \n",
    "        if name.startswith(\"Suaraindo_\"):\n",
    "            spk_id = name[len(\"Suaraindo_\"):]\n",
    "            lang = \"id\"\n",
    "        elif name.startswith(\"Suaraeng_\"):\n",
    "            spk_id = name[len(\"Suaraeng_\"):]\n",
    "            lang = \"en\"\n",
    "        elif \"_\" in name:\n",
    "            parts = name.split(\"_\")\n",
    "            spk_id = parts[-1]\n",
    "            \n",
    "        if spk_id not in speaker_map:\n",
    "            speaker_map[spk_id] = {\"id\": p, \"en\": p}\n",
    "            \n",
    "        if lang == \"id\":\n",
    "            speaker_map[spk_id][\"id\"] = p\n",
    "        elif lang == \"en\":\n",
    "            speaker_map[spk_id][\"en\"] = p\n",
    "            \n",
    "    return speaker_map\n",
    "\n",
    "def sync_single_file(src_mp3: Path, model_name: str) -> None:\n",
    "    if not src_mp3.exists(): return\n",
    "    target_dir = DRIVE_OUT / model_name\n",
    "    target_dir.mkdir(parents=True, exist_ok=True)\n",
    "    dst_mp3 = target_dir / src_mp3.name\n",
    "    shutil.copy2(src_mp3, dst_mp3)\n",
    "    print(f\"  ☁️ Disalin ke Drive: {dst_mp3.name} ({src_mp3.stat().st_size / 1024:.1f} KB)\", flush=True)\n",
    "\n",
    "# ============================================================\n",
    "# BATCH ENGINE OPTIMIZED FOR T4 (MODEL-FIRST PIPELINE)\n",
    "# ============================================================\n",
    "\n",
    "def run_batch_generation():\n",
    "    speaker_map = scan_speakers()\n",
    "    all_speakers = sorted(list(speaker_map.keys()))\n",
    "    if not all_speakers:\n",
    "        print(\"❌ Tidak ada speaker WAV/MP3/M4A yang ditemukan di folder Dataskripsi.\")\n",
    "        return\n",
    "        \n",
    "    selected_speakers = all_speakers[BATCH_START_INDEX : BATCH_START_INDEX + BATCH_MAX_COUNT]\n",
    "    print(f\"🎙️ Total Speaker Terdeteksi: {len(all_speakers)} | Memproses Batch ({len(selected_speakers)} speaker): {selected_speakers}\")\n",
    "    \n",
    "    # ────────────────────────────────────────────────────────────\n",
    "    # 1. RUN F5-TTS BATCH\n",
    "    # ────────────────────────────────────────────────────────────\n",
    "    if \"F5-TTS\" in MODELS_TO_RUN:\n",
    "        print(\"\\n==================== MODEL: F5-TTS ====================\", flush=True)\n",
    "        run(sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"f5-tts\")\n",
    "        out_dir = OUT / \"F5-TTS\"\n",
    "        out_dir.mkdir(parents=True, exist_ok=True)\n",
    "        drive_model_dir = DRIVE_OUT / \"F5-TTS\"\n",
    "        drive_model_dir.mkdir(parents=True, exist_ok=True)\n",
    "        \n",
    "        for spk in selected_speakers:\n",
    "            ref_id = speaker_map[spk][\"id\"]\n",
    "            ref_en = speaker_map[spk][\"en\"]\n",
    "            \n",
    "            for lang, text, ref in ((\"id\", TEXTS[\"id\"], ref_id), (\"en\", TEXTS[\"en\"], ref_en)):\n",
    "                final_mp3_name = f\"{spk}_{lang}.mp3\"\n",
    "                drive_mp3 = drive_model_dir / final_mp3_name\n",
    "                \n",
    "                if SKIP_EXISTING and drive_mp3.exists() and drive_mp3.stat().st_size > 1000:\n",
    "                    print(f\"  ⏩ [SKIP] F5-TTS {spk}_{lang} (Sudah ada di Drive)\", flush=True)\n",
    "                    continue\n",
    "                    \n",
    "                print(f\"  ⚡ [GENERATE] F5-TTS {spk}_{lang}...\", flush=True)\n",
    "                try:\n",
    "                    wav_out = out_dir / f\"{spk}_{lang}.wav\"\n",
    "                    mp3_out = out_dir / final_mp3_name\n",
    "                    run(\"f5-tts_infer-cli\", \"--model\", \"F5TTS_v1_Base\", \"--ref_audio\", str(ref), \"--ref_text\", \"\", \"--gen_text\", text, \"--output_dir\", str(out_dir), \"--output_file\", f\"{spk}_{lang}.wav\")\n",
    "                    mp3_from_wav(wav_out, mp3_out)\n",
    "                    sync_single_file(mp3_out, \"F5-TTS\")\n",
    "                except Exception as e:\n",
    "                    print(f\"  ❌ [ERROR] F5-TTS {spk}_{lang}: {e}\", flush=True)\n",
    "                finally:\n",
    "                    free_memory()\n",
    "        free_memory()\n",
    "\n",
    "    # ────────────────────────────────────────────────────────────\n",
    "    # 2. RUN OPENVOICE BATCH\n",
    "    # ────────────────────────────────────────────────────────────\n",
    "    if \"OpenVoice\" in MODELS_TO_RUN:\n",
    "        print(\"\\n==================== MODEL: OpenVoice ====================\", flush=True)\n",
    "        repo = ROOT / \"OpenVoice\"\n",
    "        if not repo.exists():\n",
    "            run(\"git\", \"clone\", \"--depth\", \"1\", \"https://github.com/myshell-ai/OpenVoice.git\", str(repo))\n",
    "        \n",
    "        # MeCab system dependencies for MeloTTS\n",
    "        try:\n",
    "            run(\"apt-get\", \"update\", \"-qq\")\n",
    "            run(\"apt-get\", \"install\", \"-y\", \"-qq\", \"mecab\", \"libmecab-dev\", \"mecab-ipadic-utf8\")\n",
    "        except Exception as e:\n",
    "            print(f\"  ℹ️ MeCab apt-get install skipped or non-ubuntu: {e}\", flush=True)\n",
    "            \n",
    "        run(sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"--upgrade\", \"pip\", \"setuptools\", \"wheel\")\n",
    "        run(sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"mecab-python3\", \"unidic\", \"num2words\", \"pythainlp\", \"subword_nmt\", \"cached_path\")\n",
    "        run(sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"--no-deps\", \"git+https://github.com/myshell-ai/MeloTTS.git\")\n",
    "        try:\n",
    "            run(sys.executable, \"-m\", \"unidic\", \"download\")\n",
    "        except Exception:\n",
    "            pass\n",
    "        run(sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"-e\", str(repo))\n",
    "\n",
    "        ckpt = repo / \"checkpoints_v2\"\n",
    "        if not ckpt.exists():\n",
    "            url = \"https://myshell-public-repo-host.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip\"\n",
    "            archive = ROOT / \"openvoice_checkpoints_v2.zip\"\n",
    "            urllib.request.urlretrieve(url, archive)\n",
    "            with zipfile.ZipFile(archive) as zf:\n",
    "                zf.extractall(repo)\n",
    "            archive.unlink(missing_ok=True)\n",
    "\n",
    "        import torch\n",
    "        from melo.api import TTS\n",
    "        from openvoice import se_extractor\n",
    "        from openvoice.api import ToneColorConverter\n",
    "        \n",
    "        device = \"cuda:0\" if torch.cuda.is_available() else \"cpu\"\n",
    "        converter_dir = repo / \"checkpoints_v2\" / \"converter\"\n",
    "        converter = ToneColorConverter(str(converter_dir / \"config.json\"), device=device)\n",
    "        converter.load_ckpt(str(converter_dir / \"checkpoint.pth\"))\n",
    "        \n",
    "        out_dir = OUT / \"OpenVoice\"\n",
    "        out_dir.mkdir(parents=True, exist_ok=True)\n",
    "        drive_model_dir = DRIVE_OUT / \"OpenVoice\"\n",
    "        drive_model_dir.mkdir(parents=True, exist_ok=True)\n",
    "        \n",
    "        base_tts = TTS(language=\"EN\", device=device)\n",
    "        speaker_id = next(iter(base_tts.hps.data.spk2id.values()))\n",
    "        source_se = torch.load(str(repo / \"checkpoints_v2\" / \"base_speakers\" / \"ses\" / \"en-us.pth\"), map_location=device)\n",
    "        \n",
    "        for spk in selected_speakers:\n",
    "            ref_id = speaker_map[spk][\"id\"]\n",
    "            ref_en = speaker_map[spk][\"en\"]\n",
    "            \n",
    "            try:\n",
    "                target_id, _ = se_extractor.get_se(str(ref_id), converter, vad=True, target_dir=str(ROOT / \"processed\"))\n",
    "                target_en, _ = se_extractor.get_se(str(ref_en), converter, vad=True, target_dir=str(ROOT / \"processed\"))\n",
    "                \n",
    "                for lang, text, target in ((\"id\", TEXTS[\"id\"], target_id), (\"en\", TEXTS[\"en\"], target_en)):\n",
    "                    final_mp3_name = f\"{spk}_{lang}.mp3\"\n",
    "                    drive_mp3 = drive_model_dir / final_mp3_name\n",
    "                    \n",
    "                    if SKIP_EXISTING and drive_mp3.exists() and drive_mp3.stat().st_size > 1000:\n",
    "                        print(f\"  ⏩ [SKIP] OpenVoice {spk}_{lang} (Sudah ada di Drive)\", flush=True)\n",
    "                        continue\n",
    "                        \n",
    "                    print(f\"  ⚡ [GENERATE] OpenVoice {spk}_{lang}...\", flush=True)\n",
    "                    tmp_wav = out_dir / f\"tmp_{spk}_{lang}.wav\"\n",
    "                    final_wav = out_dir / f\"{spk}_{lang}.wav\"\n",
    "                    final_mp3 = out_dir / final_mp3_name\n",
    "                    \n",
    "                    base_tts.tts_to_file(text, speaker_id, str(tmp_wav), speed=1.0)\n",
    "                    converter.convert(str(tmp_wav), source_se, target, str(final_wav), message=\"@Research\")\n",
    "                    mp3_from_wav(final_wav, final_mp3)\n",
    "                    sync_single_file(final_mp3, \"OpenVoice\")\n",
    "                    if tmp_wav.exists(): tmp_wav.unlink()\n",
    "            except Exception as e:\n",
    "                print(f\"  ❌ [ERROR] OpenVoice {spk}: {e}\", flush=True)\n",
    "            finally:\n",
    "                free_memory()\n",
    "                \n",
    "        del converter, base_tts, source_se\n",
    "        free_memory()\n",
    "\n",
    "    # ────────────────────────────────────────────────────────────\n",
    "    # 3. RUN VOXCPM BATCH (IF REQUESTED)\n",
    "    # ────────────────────────────────────────────────────────────\n",
    "    if \"VoxCPM\" in MODELS_TO_RUN:\n",
    "        print(\"\\n==================== MODEL: VoxCPM ====================\", flush=True)\n",
    "        try:\n",
    "            from voxcpm import VoxCPM\n",
    "            import soundfile as sf\n",
    "            model = VoxCPM.from_pretrained(\"OpenBMB/VoxCPM-SF\")\n",
    "            out_dir = OUT / \"VoxCPM\"\n",
    "            out_dir.mkdir(parents=True, exist_ok=True)\n",
    "            drive_model_dir = DRIVE_OUT / \"VoxCPM\"\n",
    "            drive_model_dir.mkdir(parents=True, exist_ok=True)\n",
    "            \n",
    "            for spk in selected_speakers:\n",
    "                ref_id = speaker_map[spk][\"id\"]\n",
    "                ref_en = speaker_map[spk][\"en\"]\n",
    "                \n",
    "                for lang, text, ref in ((\"id\", TEXTS[\"id\"], ref_id), (\"en\", TEXTS[\"en\"], ref_en)):\n",
    "                    final_mp3_name = f\"{spk}_{lang}.mp3\"\n",
    "                    drive_mp3 = drive_model_dir / final_mp3_name\n",
    "                    \n",
    "                    if SKIP_EXISTING and drive_mp3.exists() and drive_mp3.stat().st_size > 1000:\n",
    "                        print(f\"  ⏩ [SKIP] VoxCPM {spk}_{lang} (Sudah ada di Drive)\", flush=True)\n",
    "                        continue\n",
    "                        \n",
    "                    print(f\"  ⚡ [GENERATE] VoxCPM {spk}_{lang}...\", flush=True)\n",
    "                    try:\n",
    "                        wav = model.generate(text=text, reference_wav_path=str(ref))\n",
    "                        wav_out = out_dir / f\"{spk}_{lang}.wav\"\n",
    "                        mp3_out = out_dir / final_mp3_name\n",
    "                        sf.write(str(wav_out), wav, model.tts_model.sample_rate)\n",
    "                        mp3_from_wav(wav_out, mp3_out)\n",
    "                        sync_single_file(mp3_out, \"VoxCPM\")\n",
    "                    except Exception as e:\n",
    "                        print(f\"  ❌ [ERROR] VoxCPM {spk}_{lang}: {e}\", flush=True)\n",
    "                    finally:\n",
    "                        free_memory()\n",
    "            del model\n",
    "            free_memory()\n",
    "        except Exception as e:\n",
    "            print(f\"  ❌ [ERROR] Gagal inisialisasi VoxCPM: {e}\", flush=True)\n",
    "\n",
    "    print(\"\\n🎉 BATCH GENERATION SELESAI!\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    run_batch_generation()\n"
]

nb['cells'][3]['source'] = cell4_code

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

repo_nb_path = Path(r"c:\Users\alvin\Documents\Coolyeah\Skirpsi\Teknikal\fase 2\skripsi_residual_modulasi\Generate_Voice_Cloning_Colab.ipynb")
with open(repo_nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Fixed MeloTTS installation in both notebooks!")
